blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Personal Website
    url: https://www.xsj57.us.kg
    about: Visit my personal website for more information.